neural network might not applicable to this problem since it can't really infer anything from the data, or it was really hard to fine tune or regularize the model

# Preparation

In [1]:
import os

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import fbeta_score
from sklearn.metrics import make_scorer
from sklearn.metrics import confusion_matrix

In [2]:
DIR_PATH = "/content/drive/MyDrive/Colab Notebooks/ML CCC"

RANDOM_STATE = 42

In [3]:
f2_score = lambda y_test, y_pred: fbeta_score(y_test, y_pred, beta=2)
f2_scorer = make_scorer(fbeta_score, beta=2)

In [4]:
X_train = pd.read_csv(os.path.join(DIR_PATH, 'X_train_prep.csv')) 
X_test = pd.read_csv(os.path.join(DIR_PATH, 'X_test_prep.csv'))
y_train = pd.read_csv(os.path.join(DIR_PATH, 'y_train_prep.csv'))
y_test = pd.read_csv(os.path.join(DIR_PATH, 'y_test_prep.csv'))

In [5]:
y_train = y_train.to_numpy().ravel()
y_test = y_test.to_numpy().ravel()

In [6]:
X_val, X_test, y_val, y_test = train_test_split(
    X_test, y_test, test_size=0.6,
    random_state=RANDOM_STATE,
)

# Phase 1

In [7]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.0001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[363 153]
 [ 36  30]]
0.868910782703886
0.33557046979865773


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [8]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[371 145]
 [ 38  28]]
0.8540184235203266
0.3203661327231122


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [9]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.01,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[380 136]
 [ 39  27]]
0.8604548708629328
0.31615925058548006


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [10]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.1,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[366 150]
 [ 39  27]]
0.8546832523272098
0.3061224489795919


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [11]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=1,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[364 152]
 [ 44  22]]
0.7706840028893704
0.2511415525114155


In [12]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=10,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[  0 516]
 [  0  66]]
0.8333333333333334
0.3900709219858156


# Phase 2

In [13]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16, 8),
    alpha=0.0001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[398 118]
 [ 45  21]]
0.832089447151266
0.26054590570719605


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [14]:
nn = MLPClassifier(
    hidden_layer_sizes=(16, 8),
    alpha=0.0001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[342 174]
 [ 35  31]]
0.8190007075600066
0.3304904051172708


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Phase 3

In [15]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.0001,
    batch_size=300, max_iter=300,
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[392 124]
 [ 42  24]]
0.837202147891263
0.2912621359223301


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Phase 4

In [16]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.0001,
    batch_size='auto',
    tol=0.001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[375 141]
 [ 40  26]]
0.8385153517294984
0.3016241299303944


In [17]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=0.0001,
    batch_size='auto',
    tol=0.00001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[363 153]
 [ 36  30]]
0.868910782703886
0.33557046979865773


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Phase 5.1

In [18]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16, 8),
    alpha=0.001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[373 143]
 [ 40  26]]
0.844616197280992
0.3002309468822171


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [19]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16, 8),
    alpha=0.01,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[397 119]
 [ 43  23]]
0.8357393132445688
0.2832512315270936


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Phase 5.2

In [20]:
nn = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    alpha=0.0001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[370 146]
 [ 43  23]]
0.9321964079749547
0.2655889145496536


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


In [21]:
nn = MLPClassifier(
    hidden_layer_sizes=(64, 32),
    alpha=0.001,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[370 146]
 [ 44  22]]
0.9305837772530066
0.2546296296296296


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


# Phase 5.3

In [22]:
nn = MLPClassifier(
    hidden_layer_sizes=(256, 128),
    alpha=1,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[385 131]
 [ 46  20]]
0.8115451798042533
0.24096385542168677


# Phase 6

In [23]:
nn = MLPClassifier(
    hidden_layer_sizes=(1000,),
    alpha=1,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[334 182]
 [ 43  23]]
0.7568519327364052
0.24520255863539447


In [24]:
nn = MLPClassifier(
    hidden_layer_sizes=(1000,),
    alpha=5,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[299 217]
 [ 33  33]]
0.692255062944718
0.321011673151751


In [25]:
nn = MLPClassifier(
    hidden_layer_sizes=(1000,),
    alpha=4,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[300 216]
 [ 35  31]]
0.6951922814114302
0.30332681017612523


# Phase 7

In [30]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=5,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[303 213]
 [ 36  30]]
0.6973720229947987
0.2958579881656805


In [27]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=3,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[310 206]
 [ 41  25]]
0.7191284616856666
0.25252525252525254


In [28]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=2,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[338 178]
 [ 44  22]]
0.7286772428279256
0.2370689655172414


In [29]:
nn = MLPClassifier(
    hidden_layer_sizes=(32, 16),
    alpha=7,
    batch_size='auto',
    tol=0.0001,
    random_state=RANDOM_STATE,
).fit(X_train, y_train)
y_val_pred = nn.predict(X_val)
print(confusion_matrix(y_val, y_val_pred))
print(f2_score(y_train, nn.predict(X_train)))
print(f2_score(y_val, y_val_pred))

[[345 171]
 [ 37  29]]
0.6349675132900177
0.3125
